CREATE TABLE tabela (
	id_tabela SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	nome VARCHAR( 15 ) NOT NULL ,
	sobrenome VARCHAR( 40 ) NOT NULL ,
	email VARCHAR( 64 ) NOT NULL ,
	sexo ENUM( "M", "F" ) NOT NULL )
    ENGINE = MYISAM ;